### ISSUE TITLE
bash: target/release/rgbd: No such file or directory

### ISSUE THREAD

**Issue by Goosie** [LNP-BP/rgb-node#109]
Following the instructions further in the README and after doing the fix to add "serde" in the client section of Cargo.toml. I follow the next step: Doing the command: target/release/rgbd --data-dir ~/.rgb --bin-dir target/release -vvvv - contract fungible

Which gives the message:
bash: target/release/rgbd: No such file or directory

![rgb node nu such file or directory](https://user-images.githubusercontent.com/176074/99982504-eedbbb00-2daa-11eb-8969-93c9e9414ce9.png)

**Comment by dr-orlovsky** [comment]
Thats wierd. I also see it has not compiled rgb_node in the log. Can you list the directory content?

**Comment by Goosie** [comment]
![image](https://user-images.githubusercontent.com/176074/100441583-02d33580-30a7-11eb-8415-972882493781.png)

**Comment by Goosie** [comment]
I added the fix to add "serde" in the client section of Cargo.toml, maybe that's the case?

**Comment by Goosie** [comment]
![image](https://user-images.githubusercontent.com/176074/100441973-960c6b00-30a7-11eb-9f36-7f43c474baa1.png)

**Comment by Goosie** [comment]
![image](https://user-images.githubusercontent.com/176074/100442044-b3d9d000-30a7-11eb-8ed1-68e61e9e3b7e.png)

**Comment by Goosie** [comment]
Removed the rgb-node directory and tried to with the last checkout but still errors with unresolved import 'serde'

![image](https://user-images.githubusercontent.com/176074/100442972-2bf4c580-30a9-11eb-92ce-2474cd3016f4.png)

**Comment by dr-orlovsky** [comment]
I have witnessed the same error and spent about a day trying to understand why it happens. No success so far, this is really, really wired. Will keep you updated on my investigation

**Comment by zoedberg** [comment]
I'm pretty sure the build command requires also a `--all-features` flag, that should fix the `serde`-based errors

In this regard, no issues on the sdk side

Moreover @Goosie, you've written that you're giving this command `target/release/rgbd --data-dir ~/.rgb --bin-dir target/release -vvvv - contract fungible`, but from the screenshots I see you're giving `target/release/rgbd --data-dir ~/.rgb --bin-dir target/debug -vvvv - contract fungible`. I don't think that, launching `rgbd` built with the release profile and then link it to the binaries built with the debug profile, is a problem, but it requires building the binaries twice (once with the `--release` flag and once without)

**Comment by Goosie** [comment]
I feel almost quilty to bring this up. I had rgb-node working a couple of months earlier. But following the instructions given now, it just doesn't work for me. 
I did again removed the rgb-node dir
rm -rf rgb-node
I checked if directory really is gone cd rgb-node
sudo apt update
sudo apt-get upgrade
sudo apt install -y build-essential pkg-config libzmq3-dev libssl-dev libpq-dev cmake
git clone https://github.com/LNP-BP/rgb-node.git
cd rgb-node
sudo nano Cargo.toml (added "serde", in the client section)
cargo build --release
Gave:    Finished release [optimized] target(s) in 48.34s
target/release/rgbd --data-dir ~/.rgb --bin-dir target/release -vvvv - contract fungible
bash: target/release/rgbd: No such file or directory
... Nothing happens..

An other try:
cd $HOME
rm -rf rgb-node
git clone https://github.com/LNP-BP/rgb-node.git
cd rgb-node
sudo nano Cargo.toml (added "serde", in the client section)
cargo build --all-features
error: linking with `cc` failed: exit code: 1

An other try:
cd $HOME
rm -rf rgb-node
git clone https://github.com/LNP-BP/rgb-node.git
cd rgb-node
sudo nano Cargo.toml (added "serde", in the client section)
cargo build --release
cargo build
   Finished dev [unoptimized + debuginfo] target(s) in 1.57s

target/release/rgbd --data-dir ~/.rgb --bin-dir target/release -vvvv - contract fungible
bash: target/release/rgbd: No such file or directory

target/rgbd --data-dir ~/.rgb --bin-dir target/ -vvvv - contract fungible
bash: target/rgbd: No such file or directory

I don't want to put my self on coders or whatever, just a simple curious tester who's not afraid to try and error stuff like this. But now I'm stuck and just curious how others take their first baby steps in this code.

**Comment by zoedberg** [comment]
this command is not needed: `sudo nano Cargo.toml (added "serde", in the client section)`

the only build commands that currently work are: `cargo build --all-features` and ` cargo build --all-features --release`

to clean the repository you don't necessarily need to remove the entire directory, a `cargo clean` from the project root should be enough

from the dependencies list you've installed it seems that `libsqlite3-dev` is missing, could you please install it and then retry building with the `--all-features` flag?

**Comment by Goosie** [comment]
Yesss. This was the trick. Thanks. Now a lot of beginners would appreciate the update in the readme:
The following lines should be changed:

sudo apt install -y build-essential pkg-config libzmq3-dev libssl-dev libpq-dev cmake
into
sudo apt install -y build-essential pkg-config libzmq3-dev libssl-dev libpq-dev cmake libsqlite3-dev

cargo build --release
into
cargo build --all-features --release

And the line
target/release/rgbd --data-dir ~/.rgb --bin-dir target/release -vvvv - contract fungible
into
target/release/rgbd --data-dir ~/.rgb --bin-dir target/release -vvvv --contract fungible

Will help a lot of the starters in rgb :-)
Thanks!

**Comment by rajarshimaitra** [comment]
I think this is the same serde Issue I referenced here https://github.com/LNP-BP/rgb-node/pull/108

It seems `--all-feature` doesn't build `default` and `default` have this dependency bug. RGB file cache needs serde to work. 

The trick is to either build `--all-feature` or put `serde` inside the `default` feature like done in the above PR.

I think it would safe for now to merge that PR until we find better ways to handle this. @dr-orlovsky

**Comment by zoedberg** [comment]
I agree @rajarshimaitra, we cannot leave default build broken. It's better to find a temporary solution (yours seems good to me) and open an issue to remember to improve that. So I'll wait for @dr-orlovsky to take a decision and, based on that, I'll do a PR that just adds the missing dep or one that also changes build command

**Comment by dr-orlovsky** [comment]
With 0.2 beta 4 released pls confirm the fix of the issue (https://github.com/LNP-BP/rgb-node/releases/tag/v0.2.0-beta.4)

**Comment by zoedberg** [comment]
Yep, it works. Just opened #113 to fix deps list

**Comment by zoedberg** [comment]
@dr-orlovsky  Actually, I've just noticed that `cargo build` and `cargo build --release` (which as I said before, don't fail) aren't producing the binaries. Don't know why, but it doesn't seem correct to me

**Comment by jharveyb** [comment]
The serde dependency issue is resolved with 0.2.0-beta.4, but with the recent changes to features, no binaries are built by default.

AFAICT to test via CLI you would want `cargo build --features server,cli`

**Comment by dr-orlovsky** [comment]
It does not produce binaries since you have to provide `--all-targets` as well :) Otherwise it just produces lib files. Alternatively you can say just `--bins`

**Comment by zoedberg** [comment]
@dr-orlovsky I don't know the exact meaning of a default build, but for me, it should cover the most common case (which I think is the case of the user that wants to run rgb-node via binaries). could you give me your definition of a default build?

anyway, if we don't change this behavior, we need to change the `build` command in the README, because now it won't work as described

**Comment by dr-orlovsky** [comment]
I have no idea what default build is and have no definition for it. We are discussing how cargo works in fact; not terms how to name that. And yes, we need to update readme

**Comment by dr-orlovsky** [comment]
Was autoclosed by some PR; reopening to not forget to update README

**Comment by zoedberg** [comment]
> I have no idea what default build is and have no definition for it. I was saying about how cargo works in fact; no idea how to name it :). And yes, we need to update readme

Since we don't have a definition, I think it's best to do what normally other rust applications do. Taking electrs as a reference, its default build produces the server binary.

Therefore, instead of changing building command on the README, I think we should fix default build in order to produce the binaries (as it was before the latest fix)

**Comment by rajarshimaitra** [comment]
@zoedberg If I am not mistaken the default build is defined here 
https://github.com/LNP-BP/rgb-node/blob/fbfd21187be37336782225832e7c46446ef7e8de/Cargo.toml#L87

Its basically a collection of features that would be built when you just run `cargo build` without any specific feature flags.

**Comment by dr-orlovsky** [comment]
@zoedberg I do not see how we can have a single build that will target all main use cases for the project. One thing is when you need to have a library embedded in SDK/mobile; the other - to build a running node for the server, etc. It just simply can't be done with some single "default build command"

**Comment by zoedberg** [comment]
Sorry, probably I haven't constructed the question properly. I already know how cargo works, where default features are defined and what they imply.

What I'm trying to say is that there's no wrong or right way of defining features, since there's no enforcement by cargo. Every project is free to define features as it wants. So I think we should agree on a definition of default build for this project (and other LNP/BP ones) and stick to it, rather than continuing changing the build command behavior.

IMO the default build should provide a basic set of features, avoiding optional/unsuggested features (like vendored libs), but still providing a set that allows the user to use the sw covering the most common desired features.

For me, most of users will need binaries, so I'd change the default build in order to produce them (as it was before). For less common usages (e.g. a user than only needs cli binaries or a user that only needs the library) cargo already provides selection of features, disabling of all default features and special flags (e.g `--lib`) in order to allow (more expert) users to manually select what they really need.

So, to be clear, I was not suggesting we should target all main use cases, but the most common one (which probably is the suggested usage described in the README, which uses both server and cli binaries).

Anyway it's not up to me to decide which is the most common case, neither to decide that we should agree on a common definition of default build. So feel free to ignore my suggestions. The only important thing I see, if we decide to keep it as it is, is to change the command build on the README to add `--bins` and revert merge of #116, IMO.

**Comment by dr-orlovsky** [comment]
> When no target selection options are given, cargo build will build all binary and library targets of the selected packages.

Ok, seems like with the current README we are done here

**Comment by zoedberg** [comment]
> Ok, seems like with the current README we are done here

just checked on latest `master` (`dda36db`) and I've seen you added a `cargo build --bins`, but there's still the instruction to build it with `cargo build --release`. So there's duplication of the build commands, and inconsistency, since one suggest debug build while the second suggest a release build

**Comment by dr-orlovsky** [comment]
Don't see where this happens; so feel free to propose a PR fixing this. `cargo build --release` is the correct version
